# Generated by Django 2.2.6 on 2019-10-18 14:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=4)),
                ('descripcion', models.TextField(help_text='Ingrese una descripcion sobre el telefono', max_length=1000)),
                ('marca', models.ManyToManyField(to='productos.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='TelefonoInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unico para el celular', primary_key=True, serialize=False)),
                ('compañia', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Agotado'), ('d', 'Disponible'), ('r', 'rebajado')], default='m', help_text='Estado del libro', max_length=1)),
                ('telefono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.Telefono')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
